### ISSUE TITLE
连接打不开？

### ISSUE THREAD

**Issue by sc13sees** [oldwinter/knowledge-garden#1]
还是我打开方式不对？

**Comment by oldwinter** [comment]
是哪个链接？garden开头的嘛？我昨晚更换了DNS服务商，可能需要一定时间反应，我自己这边目前已经能正常解析打开了。你可以多刷新几次尝试一下哈，不好意思耽误你时间了。

**Comment by sc13sees** [comment]
> 是哪个链接？garden开头的嘛？我昨晚更换了DNS服务商，可能需要一定时间反应，我自己这边目前已经能正常解析打开了。你可以多刷新几次尝试一下哈，不好意思耽误你时间了。

能看了
