### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by BinkZhu** [oldwinter/knowledge-garden#3]
Sources/Articles/flomo101阅读笔记/该积累什么领域知识.md

原文：
其实少楠这篇引申很广，原作者是指在信息搜集剪藏领域，使用PARA方法或理念进行，从而时信息的搜集更有行动性和目的性，而非吃灰剪藏。

...，从而时信息的搜集...
...，从而使信息的搜集...
时 👉 使

**Comment by oldwinter** [comment]
谢谢提醒。不过这些笔记可能写给自己看为主，所以会有不少错别字，见谅。

**Comment by oldwinter** [comment]
已解决
