### ISSUE TITLE
无法更新spaced-reptition插件并且在工作区找不到图标

### ISSUE THREAD

**Issue by xiaobaicode6** [oldwinter/knowledge-garden#40]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/109948387/204416064-0b1514c0-6cba-4456-bf63-256372961d7e.png">

**Comment by oldwinter** [comment]
无法更新应该是插件的bug，等他更新就好了。
工作区找不到图标问题，你cmd➕p，找到相应命令就可以呼唤出来。

**Comment by xiaobaicode6** [comment]
感谢您 如何打赏?
