### ISSUE TITLE
某些文件名在windows系统下不兼容

### ISSUE THREAD

**Issue by shenjianpeng** [oldwinter/knowledge-garden#42]
Spaces/1-Project/第二大脑建设专题/What Is a Second Brain? - 第二大脑是什么？.md
这个文件名的第一个问号（“? ”）是英文格式的问号，在windows系统下是非法文件名的，checkout下来的时候报错

**Comment by oldwinter** [comment]
没有足够信息我无法定位呃。手头也没有win设备。要不直接download库，不要git clone哈哈。

**Comment by shenjianpeng** [comment]
ok，其实是把这个文件的名字里面的第一个问号改为中文格式的问号？就可以了。
我download没问题，就提个建议，避免后来者跟我一样折腾了。
还有，感谢分享，在你的项目里面学到很多
