### ISSUE TITLE
编辑模式下，选中文字后，上方显示的工具栏是哪个插件设置的，麻烦告知下

### ISSUE THREAD

**Issue by CallMeLD** [oldwinter/knowledge-garden#55]
如下图所示，编辑模式下，选中文字后，显示的工具栏在哪里设置的，这边看完了插件文档和各个插件的简介设置，也没有找到相关的描述，麻烦解答下，谢谢
![image](https://user-images.githubusercontent.com/49227091/221496808-c3cb6bad-dacc-44c4-9532-9d2791601326.png)

**Comment by oldwinter** [comment]
这个是make.md插件的功能，我建议关闭。我还没用上这个插件，处于考察阶段。

**Comment by CallMeLD** [comment]
嗯呢，谢啦
