### ISSUE TITLE
logseq支持常青笔记么

### ISSUE THREAD

**Issue by banduoba** [oldwinter/knowledge-garden#6]
请问如果支持的话应该怎么配置下呢

**Comment by oldwinter** [comment]
不太清楚你的具体问题是什么？常青笔记是一套理念和方法，发展于卡片笔记。现在支持双向链接的任何笔记软件，都可以用来实践常青笔记哦。

**Comment by changxvv** [comment]
[常青笔记](https://notes.andymatuschak.org/About_these_notes?stackedNotes=z4SDCZQeRo4xFEQ8H4qrSqd68ucpgE6LU155C) 是Andy提出的，知乎有一些文章的翻译。

**Comment by banduoba** [comment]
我的意思是怎么使用这个模板呢在logseq里面

**Comment by oldwinter** [comment]
> 我的意思是怎么使用这个模板呢在logseq里面

下载后，直接打开即可。logseq会自动生成配置文件的。

如果你指的是如何发布成logseq的发布网址: garden.oldwinter.top 的话，由于这个页面太大了，我把它删了，你如果感兴趣，可以在commit里面搜logseq，里面有条删除记录，还原即可。

**Comment by banduoba** [comment]
我自己用的是logseq,目前已经写了不少笔记,怎么使用常青笔记的模板呢,下载之后打开这个应该是的文章笔记内容吧

**Comment by oldwinter** [comment]
> 常青笔记是一套理念和方法，发展于卡片笔记。

哥们，看我第一条回复。常青笔记是一个方法，没有模板和固定套路。如果你还未看过相关文章，最推荐的是这本书：卡片笔记写作法 。

**Comment by oldwinter** [comment]
> [常青笔记](https://notes.andymatuschak.org/About_these_notes?stackedNotes=z4SDCZQeRo4xFEQ8H4qrSqd68ucpgE6LU155C) 是Andy提出的，知乎有一些文章的翻译。

提问的朋友就是看到我发的常青笔记搬运文章而来的。我这个就是知乎搬运而来，得到作者授权了，在知乎浏览卡片笔记非常不方便，在我数字花园里看会舒服很多：https://oldwinter.top/Sources/Articles/%E5%B8%B8%E9%9D%92%E7%AC%94%E8%AE%B0%E9%98%85%E8%AF%BB%E7%AC%94%E8%AE%B0/%E5%B8%B8%E9%9D%92%E7%AC%94%E8%AE%B0

**Comment by banduoba** [comment]
好的 好的 我去看看 谢谢
